/*
 * generated by Xtext 2.14.0
 */
package imp.lang.xtext.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import imp.lang.xtext.ide.contentassist.antlr.internal.InternalImpParser;
import imp.lang.xtext.services.ImpGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class ImpParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(ImpGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, ImpGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getStmtAccess().getAlternatives(), "rule__Stmt__Alternatives");
			builder.put(grammarAccess.getExprAccess().getAlternatives(), "rule__Expr__Alternatives");
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getBoolConstAccess().getAlternatives_1(), "rule__BoolConst__Alternatives_1");
			builder.put(grammarAccess.getUnaryOpAccess().getAlternatives(), "rule__UnaryOp__Alternatives");
			builder.put(grammarAccess.getBinaryOpAccess().getAlternatives(), "rule__BinaryOp__Alternatives");
			builder.put(grammarAccess.getArrayDeclAccess().getGroup(), "rule__ArrayDecl__Group__0");
			builder.put(grammarAccess.getArrayDeclAccess().getGroup_2(), "rule__ArrayDecl__Group_2__0");
			builder.put(grammarAccess.getArrayDeclAccess().getGroup_2_1(), "rule__ArrayDecl__Group_2_1__0");
			builder.put(grammarAccess.getSkipAccess().getGroup(), "rule__Skip__Group__0");
			builder.put(grammarAccess.getAssignAccess().getGroup(), "rule__Assign__Group__0");
			builder.put(grammarAccess.getAssignAccess().getGroup_1(), "rule__Assign__Group_1__0");
			builder.put(grammarAccess.getBlockAccess().getGroup(), "rule__Block__Group__0");
			builder.put(grammarAccess.getBlockAccess().getGroup_2(), "rule__Block__Group_2__0");
			builder.put(grammarAccess.getBlockAccess().getGroup_2_1(), "rule__Block__Group_2_1__0");
			builder.put(grammarAccess.getIfAccess().getGroup(), "rule__If__Group__0");
			builder.put(grammarAccess.getIfAccess().getGroup_5(), "rule__If__Group_5__0");
			builder.put(grammarAccess.getWhileAccess().getGroup(), "rule__While__Group__0");
			builder.put(grammarAccess.getIntConstAccess().getGroup(), "rule__IntConst__Group__0");
			builder.put(grammarAccess.getBoolConstAccess().getGroup(), "rule__BoolConst__Group__0");
			builder.put(grammarAccess.getVarAccess().getGroup(), "rule__Var__Group__0");
			builder.put(grammarAccess.getVarAccess().getGroup_2(), "rule__Var__Group_2__0");
			builder.put(grammarAccess.getUnaryAccess().getGroup(), "rule__Unary__Group__0");
			builder.put(grammarAccess.getBinaryAccess().getGroup(), "rule__Binary__Group__0");
			builder.put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
			builder.put(grammarAccess.getArrayDeclAccess().getValuesAssignment_2_0(), "rule__ArrayDecl__ValuesAssignment_2_0");
			builder.put(grammarAccess.getArrayDeclAccess().getValuesAssignment_2_1_1(), "rule__ArrayDecl__ValuesAssignment_2_1_1");
			builder.put(grammarAccess.getAssignAccess().getNameAssignment_0(), "rule__Assign__NameAssignment_0");
			builder.put(grammarAccess.getAssignAccess().getIndexAssignment_1_1(), "rule__Assign__IndexAssignment_1_1");
			builder.put(grammarAccess.getAssignAccess().getExpAssignment_3(), "rule__Assign__ExpAssignment_3");
			builder.put(grammarAccess.getBlockAccess().getStmtsAssignment_2_0(), "rule__Block__StmtsAssignment_2_0");
			builder.put(grammarAccess.getBlockAccess().getStmtsAssignment_2_1_1(), "rule__Block__StmtsAssignment_2_1_1");
			builder.put(grammarAccess.getIfAccess().getCondAssignment_2(), "rule__If__CondAssignment_2");
			builder.put(grammarAccess.getIfAccess().getLhsAssignment_4(), "rule__If__LhsAssignment_4");
			builder.put(grammarAccess.getIfAccess().getRhsAssignment_5_1(), "rule__If__RhsAssignment_5_1");
			builder.put(grammarAccess.getWhileAccess().getCondAssignment_2(), "rule__While__CondAssignment_2");
			builder.put(grammarAccess.getWhileAccess().getBodyAssignment_4(), "rule__While__BodyAssignment_4");
			builder.put(grammarAccess.getIntConstAccess().getValueAssignment_1(), "rule__IntConst__ValueAssignment_1");
			builder.put(grammarAccess.getBoolConstAccess().getValueAssignment_1_0(), "rule__BoolConst__ValueAssignment_1_0");
			builder.put(grammarAccess.getVarAccess().getNameAssignment_1(), "rule__Var__NameAssignment_1");
			builder.put(grammarAccess.getVarAccess().getIndexAssignment_2_1(), "rule__Var__IndexAssignment_2_1");
			builder.put(grammarAccess.getUnaryAccess().getOpAssignment_2(), "rule__Unary__OpAssignment_2");
			builder.put(grammarAccess.getUnaryAccess().getExprAssignment_3(), "rule__Unary__ExprAssignment_3");
			builder.put(grammarAccess.getBinaryAccess().getOpAssignment_2(), "rule__Binary__OpAssignment_2");
			builder.put(grammarAccess.getBinaryAccess().getLhsAssignment_4(), "rule__Binary__LhsAssignment_4");
			builder.put(grammarAccess.getBinaryAccess().getRhsAssignment_6(), "rule__Binary__RhsAssignment_6");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private ImpGrammarAccess grammarAccess;

	@Override
	protected InternalImpParser createParser() {
		InternalImpParser result = new InternalImpParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public ImpGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ImpGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
