/*
 * generated by Xtext 2.14.0
 */
package imp.lang.xtext.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class ImpUiModule extends AbstractImpUiModule {
}
