/*
 * generated by Xtext 2.14.0
 */
package imp.lang.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractImpScopeProvider extends DelegatingScopeProvider {
}
