/*
 * generated by Xtext 2.14.0
 */
package org.tetrabox.minijava.xtext.fortest.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.tetrabox.minijava.xtext.fortest.ui.internal.FortestActivator;

public class MiniJavaUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return FortestActivator.getInstance().getInjector("org.tetrabox.minijava.xtext.fortest.MiniJava");
	}

}
