<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="miniJava" nsURI="http://www.example.org/minijava/MiniJava" nsPrefix="miniJava">
  <eClassifiers xsi:type="ecore:EClass" name="Program">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="imports" upperBound="-1"
        eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Import"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classes" upperBound="-1"
        eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//TypeDeclaration"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="state" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//State"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Import">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="importedNamespace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeDeclaration" eSuperTypes="/org.tetrabox.minijava.xtext/model/MiniJava.ecore#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="accessLevel" eType="ecore:EEnum /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//AccessLevel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="implementz" unique="false"
        upperBound="-1" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Interface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="members" upperBound="-1"
        eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Member"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Clazz" eSuperTypes="/org.tetrabox.minijava.xtext/model/MiniJava.ecore#//TypeDeclaration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isabstract" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="superClass" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Clazz"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Interface" eSuperTypes="/org.tetrabox.minijava.xtext/model/MiniJava.ecore#//TypeDeclaration"/>
  <eClassifiers xsi:type="ecore:EClass" name="Member" eSuperTypes="/org.tetrabox.minijava.xtext/model/MiniJava.ecore#//TypedDeclaration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="access" eType="ecore:EEnum /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//AccessLevel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Method" eSuperTypes="/org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Member">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isabstract" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isstatic" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="params" upperBound="-1"
        eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Parameter"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Block"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter" eSuperTypes="/org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Symbol"/>
  <eClassifiers xsi:type="ecore:EClass" name="Field" eSuperTypes="/org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Member">
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultValue" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AccessLevel">
    <eLiterals name="PRIVATE" literal="private"/>
    <eLiterals name="PROTECTED" value="1" literal="protected"/>
    <eLiterals name="PUBLIC" value="2" literal="public"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Block" eSuperTypes="/org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statements" upperBound="-1"
        eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Statement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Statement"/>
  <eClassifiers xsi:type="ecore:EClass" name="PrintStatement" eSuperTypes="/org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Return" eSuperTypes="/org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IfStatement" eSuperTypes="/org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="thenBlock" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Block"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elseBlock" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Block"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WhileStatement" eSuperTypes="/org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Block"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ForStatement" eSuperTypes="/org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="declaration" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Assignment"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="progression" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Assignment"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Block"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeRef"/>
  <eClassifiers xsi:type="ecore:EClass" name="SingleTypeRef" eSuperTypes="/org.tetrabox.minijava.xtext/model/MiniJava.ecore#//TypeRef"/>
  <eClassifiers xsi:type="ecore:EClass" name="ClassRef" eSuperTypes="/org.tetrabox.minijava.xtext/model/MiniJava.ecore#//SingleTypeRef">
    <eStructuralFeatures xsi:type="ecore:EReference" name="referencedClass" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//TypeDeclaration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypedDeclaration" eSuperTypes="/org.tetrabox.minijava.xtext/model/MiniJava.ecore#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeRef" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//TypeRef"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Symbol" eSuperTypes="/org.tetrabox.minijava.xtext/model/MiniJava.ecore#//TypedDeclaration"/>
  <eClassifiers xsi:type="ecore:EClass" name="VariableDeclaration" eSuperTypes="/org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Symbol /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Assignee"/>
  <eClassifiers xsi:type="ecore:EClass" name="Assignment" eSuperTypes="/org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignee" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Assignee"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Assignee"/>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" eSuperTypes="/org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Statement /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Assignee"/>
  <eClassifiers xsi:type="ecore:EClass" name="ArrayTypeRef" eSuperTypes="/org.tetrabox.minijava.xtext/model/MiniJava.ecore#//TypeRef">
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeRef" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//SingleTypeRef"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerTypeRef" eSuperTypes="/org.tetrabox.minijava.xtext/model/MiniJava.ecore#//SingleTypeRef"/>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanTypeRef" eSuperTypes="/org.tetrabox.minijava.xtext/model/MiniJava.ecore#//SingleTypeRef"/>
  <eClassifiers xsi:type="ecore:EClass" name="StringTypeRef" eSuperTypes="/org.tetrabox.minijava.xtext/model/MiniJava.ecore#//SingleTypeRef"/>
  <eClassifiers xsi:type="ecore:EClass" name="VoidTypeRef" eSuperTypes="/org.tetrabox.minijava.xtext/model/MiniJava.ecore#//SingleTypeRef"/>
  <eClassifiers xsi:type="ecore:EClass" name="Or" eSuperTypes="/org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="And" eSuperTypes="/org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Equality" eSuperTypes="/org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Inequality" eSuperTypes="/org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SuperiorOrEqual" eSuperTypes="/org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InferiorOrEqual" eSuperTypes="/org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Superior" eSuperTypes="/org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Inferior" eSuperTypes="/org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Plus" eSuperTypes="/org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Minus" eSuperTypes="/org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Multiplication" eSuperTypes="/org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Division" eSuperTypes="/org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArrayAccess" eSuperTypes="/org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="object" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="index" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArrayLength" eSuperTypes="/org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="array" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Not" eSuperTypes="/org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Neg" eSuperTypes="/org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FieldAccess" eSuperTypes="/org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="receiver" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="field" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Field"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MethodCall" eSuperTypes="/org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="receiver" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="method" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Method"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="args" upperBound="-1" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringConstant" eSuperTypes="/org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntConstant" eSuperTypes="/org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BoolConstant" eSuperTypes="/org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="This" eSuperTypes="/org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="Super" eSuperTypes="/org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="Null" eSuperTypes="/org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="NewObject" eSuperTypes="/org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Clazz"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="args" upperBound="-1" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NewArray" eSuperTypes="/org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//TypeRef"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="size" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SymbolRef" eSuperTypes="/org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="symbol" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Symbol"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Context">
    <eAnnotations source="aspect"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bindings" upperBound="-1"
        eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//SymbolBinding"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentContext" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Context"
        eOpposite="/org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Context/childContext"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="childContext" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Context"
        containment="true" eOpposite="/org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Context/parentContext"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cache" upperBound="-1"
        eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//SymbolToSymbolBindingMap"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Value">
    <eAnnotations source="aspect"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerValue" eSuperTypes="/org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Value">
    <eAnnotations source="aspect"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SymbolBinding">
    <eAnnotations source="aspect"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Value"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="symbol" lowerBound="1"
        eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Symbol"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FieldBinding">
    <eAnnotations source="aspect"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="field" lowerBound="1" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Field"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Value"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringValue" eSuperTypes="/org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Value">
    <eAnnotations source="aspect"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanValue" eSuperTypes="/org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Value">
    <eAnnotations source="aspect"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OutputStream">
    <eAnnotations source="aspect"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stream" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="State">
    <eAnnotations source="aspect"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rootFrame" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Frame"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="objectsHeap" upperBound="-1"
        eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//ObjectInstance"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputStream" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//OutputStream"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arraysHeap" upperBound="-1"
        eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//ArrayInstance"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contextCache" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Context"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="frameCache" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Frame"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Frame">
    <eAnnotations source="aspect"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="call" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Call"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instance" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//ObjectInstance"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="childFrame" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Frame"
        containment="true" eOpposite="/org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Frame/parentFrame"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentFrame" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Frame"
        eOpposite="/org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Frame/childFrame"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rootContext" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Context"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="returnValue" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Value"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NullValue" eSuperTypes="/org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Value">
    <eAnnotations source="aspect"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Call" abstract="true">
    <eAnnotations source="aspect"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NewCall" eSuperTypes="/org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Call">
    <eAnnotations source="aspect"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="newz" lowerBound="1" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//NewObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MethodCall2" eSuperTypes="/org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Call">
    <eAnnotations source="aspect"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="methodcall" lowerBound="1"
        eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//MethodCall"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectInstance">
    <eAnnotations source="aspect"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fieldbindings" upperBound="-1"
        eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//FieldBinding"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Clazz"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArrayInstance">
    <eAnnotations source="aspect"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" upperBound="-1"
        eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Value"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectRefValue" eSuperTypes="/org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Value">
    <eAnnotations source="aspect"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instance" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//ObjectInstance"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArrayRefValue" eSuperTypes="/org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Value">
    <eAnnotations source="aspect"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instance" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//ArrayInstance"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SymbolToSymbolBindingMap" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="key" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//Symbol"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="ecore:EClass /org.tetrabox.minijava.xtext/model/MiniJava.ecore#//SymbolBinding"/>
  </eClassifiers>
</ecore:EPackage>
