/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.myDsl.MyDslFactory
 * @model kind="package"
 * @generated
 */
public interface MyDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "myDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/MyDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "myDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDslPackage eINSTANCE = org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.FileImpl <em>File</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.FileImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getFile()
   * @generated
   */
  int FILE = 0;

  /**
   * The feature id for the '<em><b>Commands</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILE__COMMANDS = 0;

  /**
   * The number of structural features of the '<em>File</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.TopLevelCmdImpl <em>Top Level Cmd</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.TopLevelCmdImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getTopLevelCmd()
   * @generated
   */
  int TOP_LEVEL_CMD = 1;

  /**
   * The number of structural features of the '<em>Top Level Cmd</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TOP_LEVEL_CMD_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ExprImpl <em>Expr</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ExprImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getExpr()
   * @generated
   */
  int EXPR = 2;

  /**
   * The number of structural features of the '<em>Expr</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.DefImpl <em>Def</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.DefImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getDef()
   * @generated
   */
  int DEF = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEF__NAME = TOP_LEVEL_CMD_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEF__EXPR = TOP_LEVEL_CMD_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Def</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEF_FEATURE_COUNT = TOP_LEVEL_CMD_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.AppImpl <em>App</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.AppImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getApp()
   * @generated
   */
  int APP = 4;

  /**
   * The feature id for the '<em><b>Lhs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int APP__LHS = TOP_LEVEL_CMD_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Rhs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int APP__RHS = TOP_LEVEL_CMD_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>App</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int APP_FEATURE_COUNT = TOP_LEVEL_CMD_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.VarImpl <em>Var</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.VarImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getVar()
   * @generated
   */
  int VAR = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR__NAME = TOP_LEVEL_CMD_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Var</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_FEATURE_COUNT = TOP_LEVEL_CMD_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ThisImpl <em>This</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ThisImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getThis()
   * @generated
   */
  int THIS = 6;

  /**
   * The number of structural features of the '<em>This</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int THIS_FEATURE_COUNT = TOP_LEVEL_CMD_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.BoolImpl <em>Bool</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.BoolImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getBool()
   * @generated
   */
  int BOOL = 7;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOL__VALUE = TOP_LEVEL_CMD_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Bool</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOL_FEATURE_COUNT = TOP_LEVEL_CMD_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.IntImpl <em>Int</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.IntImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getInt()
   * @generated
   */
  int INT = 8;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT__VALUE = TOP_LEVEL_CMD_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Int</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_FEATURE_COUNT = TOP_LEVEL_CMD_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.SkipImpl <em>Skip</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.SkipImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getSkip()
   * @generated
   */
  int SKIP = 9;

  /**
   * The number of structural features of the '<em>Skip</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SKIP_FEATURE_COUNT = TOP_LEVEL_CMD_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ProjectImpl <em>Project</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ProjectImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getProject()
   * @generated
   */
  int PROJECT = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROJECT__NAME = TOP_LEVEL_CMD_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROJECT__EXP = TOP_LEVEL_CMD_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Project</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROJECT_FEATURE_COUNT = TOP_LEVEL_CMD_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.BObjectImpl <em>BObject</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.BObjectImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getBObject()
   * @generated
   */
  int BOBJECT = 11;

  /**
   * The feature id for the '<em><b>Fields</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOBJECT__FIELDS = TOP_LEVEL_CMD_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>BObject</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOBJECT_FEATURE_COUNT = TOP_LEVEL_CMD_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.CopyImpl <em>Copy</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.CopyImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getCopy()
   * @generated
   */
  int COPY = 12;

  /**
   * The feature id for the '<em><b>Copy</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COPY__COPY = TOP_LEVEL_CMD_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Copy</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COPY_FEATURE_COUNT = TOP_LEVEL_CMD_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.WithImpl <em>With</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.WithImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getWith()
   * @generated
   */
  int WITH = 13;

  /**
   * The feature id for the '<em><b>Lhs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WITH__LHS = TOP_LEVEL_CMD_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Rhs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WITH__RHS = TOP_LEVEL_CMD_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>With</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WITH_FEATURE_COUNT = TOP_LEVEL_CMD_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.NotImpl <em>Not</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.NotImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getNot()
   * @generated
   */
  int NOT = 14;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOT__VALUE = TOP_LEVEL_CMD_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Not</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOT_FEATURE_COUNT = TOP_LEVEL_CMD_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.IfImpl <em>If</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.IfImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getIf()
   * @generated
   */
  int IF = 15;

  /**
   * The feature id for the '<em><b>Cond</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF__COND = TOP_LEVEL_CMD_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Thn</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF__THN = TOP_LEVEL_CMD_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Els</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF__ELS = TOP_LEVEL_CMD_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>If</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_FEATURE_COUNT = TOP_LEVEL_CMD_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.LetImpl <em>Let</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.LetImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getLet()
   * @generated
   */
  int LET = 16;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LET__NAME = TOP_LEVEL_CMD_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Lhs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LET__LHS = TOP_LEVEL_CMD_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Rhs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LET__RHS = TOP_LEVEL_CMD_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Let</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LET_FEATURE_COUNT = TOP_LEVEL_CMD_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.FunImpl <em>Fun</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.FunImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getFun()
   * @generated
   */
  int FUN = 17;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUN__NAME = TOP_LEVEL_CMD_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUN__BODY = TOP_LEVEL_CMD_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Fun</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUN_FEATURE_COUNT = TOP_LEVEL_CMD_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.AssignImpl <em>Assign</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.AssignImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getAssign()
   * @generated
   */
  int ASSIGN = 18;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSIGN__NAME = TOP_LEVEL_CMD_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Lhs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSIGN__LHS = TOP_LEVEL_CMD_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Rhs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSIGN__RHS = TOP_LEVEL_CMD_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Assign</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSIGN_FEATURE_COUNT = TOP_LEVEL_CMD_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ArithOpPlusImpl <em>Arith Op Plus</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ArithOpPlusImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getArithOpPlus()
   * @generated
   */
  int ARITH_OP_PLUS = 19;

  /**
   * The feature id for the '<em><b>Lhs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARITH_OP_PLUS__LHS = TOP_LEVEL_CMD_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Rhs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARITH_OP_PLUS__RHS = TOP_LEVEL_CMD_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Arith Op Plus</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARITH_OP_PLUS_FEATURE_COUNT = TOP_LEVEL_CMD_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ArithOpMinusImpl <em>Arith Op Minus</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ArithOpMinusImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getArithOpMinus()
   * @generated
   */
  int ARITH_OP_MINUS = 20;

  /**
   * The feature id for the '<em><b>Lhs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARITH_OP_MINUS__LHS = TOP_LEVEL_CMD_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Rhs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARITH_OP_MINUS__RHS = TOP_LEVEL_CMD_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Arith Op Minus</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARITH_OP_MINUS_FEATURE_COUNT = TOP_LEVEL_CMD_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ArithOpTimesImpl <em>Arith Op Times</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ArithOpTimesImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getArithOpTimes()
   * @generated
   */
  int ARITH_OP_TIMES = 21;

  /**
   * The feature id for the '<em><b>Lhs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARITH_OP_TIMES__LHS = TOP_LEVEL_CMD_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Rhs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARITH_OP_TIMES__RHS = TOP_LEVEL_CMD_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Arith Op Times</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARITH_OP_TIMES_FEATURE_COUNT = TOP_LEVEL_CMD_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ArithOpDivideImpl <em>Arith Op Divide</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ArithOpDivideImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getArithOpDivide()
   * @generated
   */
  int ARITH_OP_DIVIDE = 22;

  /**
   * The feature id for the '<em><b>Lhs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARITH_OP_DIVIDE__LHS = TOP_LEVEL_CMD_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Rhs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARITH_OP_DIVIDE__RHS = TOP_LEVEL_CMD_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Arith Op Divide</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARITH_OP_DIVIDE_FEATURE_COUNT = TOP_LEVEL_CMD_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ArithOpRemainderImpl <em>Arith Op Remainder</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ArithOpRemainderImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getArithOpRemainder()
   * @generated
   */
  int ARITH_OP_REMAINDER = 23;

  /**
   * The feature id for the '<em><b>Lhs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARITH_OP_REMAINDER__LHS = TOP_LEVEL_CMD_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Rhs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARITH_OP_REMAINDER__RHS = TOP_LEVEL_CMD_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Arith Op Remainder</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARITH_OP_REMAINDER_FEATURE_COUNT = TOP_LEVEL_CMD_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.BoolOpAndImpl <em>Bool Op And</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.BoolOpAndImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getBoolOpAnd()
   * @generated
   */
  int BOOL_OP_AND = 24;

  /**
   * The feature id for the '<em><b>Lhs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOL_OP_AND__LHS = TOP_LEVEL_CMD_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Rhs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOL_OP_AND__RHS = TOP_LEVEL_CMD_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Bool Op And</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOL_OP_AND_FEATURE_COUNT = TOP_LEVEL_CMD_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.BoolOpOrImpl <em>Bool Op Or</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.BoolOpOrImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getBoolOpOr()
   * @generated
   */
  int BOOL_OP_OR = 25;

  /**
   * The feature id for the '<em><b>Lhs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOL_OP_OR__LHS = TOP_LEVEL_CMD_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Rhs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOL_OP_OR__RHS = TOP_LEVEL_CMD_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Bool Op Or</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOL_OP_OR_FEATURE_COUNT = TOP_LEVEL_CMD_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.SeqImpl <em>Seq</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.SeqImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getSeq()
   * @generated
   */
  int SEQ = 26;

  /**
   * The feature id for the '<em><b>Lhs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SEQ__LHS = TOP_LEVEL_CMD_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Rhs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SEQ__RHS = TOP_LEVEL_CMD_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Seq</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SEQ_FEATURE_COUNT = TOP_LEVEL_CMD_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.CmpOpEqualImpl <em>Cmp Op Equal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.CmpOpEqualImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getCmpOpEqual()
   * @generated
   */
  int CMP_OP_EQUAL = 27;

  /**
   * The feature id for the '<em><b>Lhs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CMP_OP_EQUAL__LHS = TOP_LEVEL_CMD_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Rhs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CMP_OP_EQUAL__RHS = TOP_LEVEL_CMD_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Cmp Op Equal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CMP_OP_EQUAL_FEATURE_COUNT = TOP_LEVEL_CMD_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.CmpOpUnequalImpl <em>Cmp Op Unequal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.CmpOpUnequalImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getCmpOpUnequal()
   * @generated
   */
  int CMP_OP_UNEQUAL = 28;

  /**
   * The feature id for the '<em><b>Lhs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CMP_OP_UNEQUAL__LHS = TOP_LEVEL_CMD_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Rhs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CMP_OP_UNEQUAL__RHS = TOP_LEVEL_CMD_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Cmp Op Unequal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CMP_OP_UNEQUAL_FEATURE_COUNT = TOP_LEVEL_CMD_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.CmpOpLessImpl <em>Cmp Op Less</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.CmpOpLessImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getCmpOpLess()
   * @generated
   */
  int CMP_OP_LESS = 29;

  /**
   * The feature id for the '<em><b>Lhs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CMP_OP_LESS__LHS = TOP_LEVEL_CMD_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Rhs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CMP_OP_LESS__RHS = TOP_LEVEL_CMD_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Cmp Op Less</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CMP_OP_LESS_FEATURE_COUNT = TOP_LEVEL_CMD_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.FieldImpl <em>Field</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.FieldImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getField()
   * @generated
   */
  int FIELD = 30;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIELD__NAME = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIELD__VALUE = 1;

  /**
   * The number of structural features of the '<em>Field</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIELD_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.File <em>File</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>File</em>'.
   * @see org.xtext.example.mydsl.myDsl.File
   * @generated
   */
  EClass getFile();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.File#getCommands <em>Commands</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Commands</em>'.
   * @see org.xtext.example.mydsl.myDsl.File#getCommands()
   * @see #getFile()
   * @generated
   */
  EReference getFile_Commands();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.TopLevelCmd <em>Top Level Cmd</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Top Level Cmd</em>'.
   * @see org.xtext.example.mydsl.myDsl.TopLevelCmd
   * @generated
   */
  EClass getTopLevelCmd();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Expr <em>Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expr</em>'.
   * @see org.xtext.example.mydsl.myDsl.Expr
   * @generated
   */
  EClass getExpr();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Def <em>Def</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Def</em>'.
   * @see org.xtext.example.mydsl.myDsl.Def
   * @generated
   */
  EClass getDef();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Def#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Def#getName()
   * @see #getDef()
   * @generated
   */
  EAttribute getDef_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Def#getExpr <em>Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expr</em>'.
   * @see org.xtext.example.mydsl.myDsl.Def#getExpr()
   * @see #getDef()
   * @generated
   */
  EReference getDef_Expr();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.App <em>App</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>App</em>'.
   * @see org.xtext.example.mydsl.myDsl.App
   * @generated
   */
  EClass getApp();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.App#getLhs <em>Lhs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Lhs</em>'.
   * @see org.xtext.example.mydsl.myDsl.App#getLhs()
   * @see #getApp()
   * @generated
   */
  EReference getApp_Lhs();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.App#getRhs <em>Rhs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Rhs</em>'.
   * @see org.xtext.example.mydsl.myDsl.App#getRhs()
   * @see #getApp()
   * @generated
   */
  EReference getApp_Rhs();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Var <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Var</em>'.
   * @see org.xtext.example.mydsl.myDsl.Var
   * @generated
   */
  EClass getVar();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Var#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Var#getName()
   * @see #getVar()
   * @generated
   */
  EAttribute getVar_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.This <em>This</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>This</em>'.
   * @see org.xtext.example.mydsl.myDsl.This
   * @generated
   */
  EClass getThis();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Bool <em>Bool</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Bool</em>'.
   * @see org.xtext.example.mydsl.myDsl.Bool
   * @generated
   */
  EClass getBool();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Bool#isValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.example.mydsl.myDsl.Bool#isValue()
   * @see #getBool()
   * @generated
   */
  EAttribute getBool_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Int <em>Int</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Int</em>'.
   * @see org.xtext.example.mydsl.myDsl.Int
   * @generated
   */
  EClass getInt();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Int#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.example.mydsl.myDsl.Int#getValue()
   * @see #getInt()
   * @generated
   */
  EAttribute getInt_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Skip <em>Skip</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Skip</em>'.
   * @see org.xtext.example.mydsl.myDsl.Skip
   * @generated
   */
  EClass getSkip();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Project <em>Project</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Project</em>'.
   * @see org.xtext.example.mydsl.myDsl.Project
   * @generated
   */
  EClass getProject();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Project#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Project#getName()
   * @see #getProject()
   * @generated
   */
  EAttribute getProject_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Project#getExp <em>Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Exp</em>'.
   * @see org.xtext.example.mydsl.myDsl.Project#getExp()
   * @see #getProject()
   * @generated
   */
  EReference getProject_Exp();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.BObject <em>BObject</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>BObject</em>'.
   * @see org.xtext.example.mydsl.myDsl.BObject
   * @generated
   */
  EClass getBObject();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.BObject#getFields <em>Fields</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Fields</em>'.
   * @see org.xtext.example.mydsl.myDsl.BObject#getFields()
   * @see #getBObject()
   * @generated
   */
  EReference getBObject_Fields();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Copy <em>Copy</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Copy</em>'.
   * @see org.xtext.example.mydsl.myDsl.Copy
   * @generated
   */
  EClass getCopy();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Copy#getCopy <em>Copy</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Copy</em>'.
   * @see org.xtext.example.mydsl.myDsl.Copy#getCopy()
   * @see #getCopy()
   * @generated
   */
  EReference getCopy_Copy();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.With <em>With</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>With</em>'.
   * @see org.xtext.example.mydsl.myDsl.With
   * @generated
   */
  EClass getWith();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.With#getLhs <em>Lhs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Lhs</em>'.
   * @see org.xtext.example.mydsl.myDsl.With#getLhs()
   * @see #getWith()
   * @generated
   */
  EReference getWith_Lhs();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.With#getRhs <em>Rhs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Rhs</em>'.
   * @see org.xtext.example.mydsl.myDsl.With#getRhs()
   * @see #getWith()
   * @generated
   */
  EReference getWith_Rhs();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Not <em>Not</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Not</em>'.
   * @see org.xtext.example.mydsl.myDsl.Not
   * @generated
   */
  EClass getNot();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Not#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see org.xtext.example.mydsl.myDsl.Not#getValue()
   * @see #getNot()
   * @generated
   */
  EReference getNot_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.If <em>If</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>If</em>'.
   * @see org.xtext.example.mydsl.myDsl.If
   * @generated
   */
  EClass getIf();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.If#getCond <em>Cond</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Cond</em>'.
   * @see org.xtext.example.mydsl.myDsl.If#getCond()
   * @see #getIf()
   * @generated
   */
  EReference getIf_Cond();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.If#getThn <em>Thn</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Thn</em>'.
   * @see org.xtext.example.mydsl.myDsl.If#getThn()
   * @see #getIf()
   * @generated
   */
  EReference getIf_Thn();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.If#getEls <em>Els</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Els</em>'.
   * @see org.xtext.example.mydsl.myDsl.If#getEls()
   * @see #getIf()
   * @generated
   */
  EReference getIf_Els();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Let <em>Let</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Let</em>'.
   * @see org.xtext.example.mydsl.myDsl.Let
   * @generated
   */
  EClass getLet();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Let#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Let#getName()
   * @see #getLet()
   * @generated
   */
  EAttribute getLet_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Let#getLhs <em>Lhs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Lhs</em>'.
   * @see org.xtext.example.mydsl.myDsl.Let#getLhs()
   * @see #getLet()
   * @generated
   */
  EReference getLet_Lhs();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Let#getRhs <em>Rhs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Rhs</em>'.
   * @see org.xtext.example.mydsl.myDsl.Let#getRhs()
   * @see #getLet()
   * @generated
   */
  EReference getLet_Rhs();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Fun <em>Fun</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Fun</em>'.
   * @see org.xtext.example.mydsl.myDsl.Fun
   * @generated
   */
  EClass getFun();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Fun#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Fun#getName()
   * @see #getFun()
   * @generated
   */
  EAttribute getFun_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Fun#getBody <em>Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Body</em>'.
   * @see org.xtext.example.mydsl.myDsl.Fun#getBody()
   * @see #getFun()
   * @generated
   */
  EReference getFun_Body();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Assign <em>Assign</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Assign</em>'.
   * @see org.xtext.example.mydsl.myDsl.Assign
   * @generated
   */
  EClass getAssign();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Assign#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Assign#getName()
   * @see #getAssign()
   * @generated
   */
  EAttribute getAssign_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Assign#getLhs <em>Lhs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Lhs</em>'.
   * @see org.xtext.example.mydsl.myDsl.Assign#getLhs()
   * @see #getAssign()
   * @generated
   */
  EReference getAssign_Lhs();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Assign#getRhs <em>Rhs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Rhs</em>'.
   * @see org.xtext.example.mydsl.myDsl.Assign#getRhs()
   * @see #getAssign()
   * @generated
   */
  EReference getAssign_Rhs();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.ArithOpPlus <em>Arith Op Plus</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Arith Op Plus</em>'.
   * @see org.xtext.example.mydsl.myDsl.ArithOpPlus
   * @generated
   */
  EClass getArithOpPlus();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.ArithOpPlus#getLhs <em>Lhs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Lhs</em>'.
   * @see org.xtext.example.mydsl.myDsl.ArithOpPlus#getLhs()
   * @see #getArithOpPlus()
   * @generated
   */
  EReference getArithOpPlus_Lhs();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.ArithOpPlus#getRhs <em>Rhs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Rhs</em>'.
   * @see org.xtext.example.mydsl.myDsl.ArithOpPlus#getRhs()
   * @see #getArithOpPlus()
   * @generated
   */
  EReference getArithOpPlus_Rhs();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.ArithOpMinus <em>Arith Op Minus</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Arith Op Minus</em>'.
   * @see org.xtext.example.mydsl.myDsl.ArithOpMinus
   * @generated
   */
  EClass getArithOpMinus();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.ArithOpMinus#getLhs <em>Lhs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Lhs</em>'.
   * @see org.xtext.example.mydsl.myDsl.ArithOpMinus#getLhs()
   * @see #getArithOpMinus()
   * @generated
   */
  EReference getArithOpMinus_Lhs();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.ArithOpMinus#getRhs <em>Rhs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Rhs</em>'.
   * @see org.xtext.example.mydsl.myDsl.ArithOpMinus#getRhs()
   * @see #getArithOpMinus()
   * @generated
   */
  EReference getArithOpMinus_Rhs();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.ArithOpTimes <em>Arith Op Times</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Arith Op Times</em>'.
   * @see org.xtext.example.mydsl.myDsl.ArithOpTimes
   * @generated
   */
  EClass getArithOpTimes();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.ArithOpTimes#getLhs <em>Lhs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Lhs</em>'.
   * @see org.xtext.example.mydsl.myDsl.ArithOpTimes#getLhs()
   * @see #getArithOpTimes()
   * @generated
   */
  EReference getArithOpTimes_Lhs();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.ArithOpTimes#getRhs <em>Rhs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Rhs</em>'.
   * @see org.xtext.example.mydsl.myDsl.ArithOpTimes#getRhs()
   * @see #getArithOpTimes()
   * @generated
   */
  EReference getArithOpTimes_Rhs();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.ArithOpDivide <em>Arith Op Divide</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Arith Op Divide</em>'.
   * @see org.xtext.example.mydsl.myDsl.ArithOpDivide
   * @generated
   */
  EClass getArithOpDivide();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.ArithOpDivide#getLhs <em>Lhs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Lhs</em>'.
   * @see org.xtext.example.mydsl.myDsl.ArithOpDivide#getLhs()
   * @see #getArithOpDivide()
   * @generated
   */
  EReference getArithOpDivide_Lhs();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.ArithOpDivide#getRhs <em>Rhs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Rhs</em>'.
   * @see org.xtext.example.mydsl.myDsl.ArithOpDivide#getRhs()
   * @see #getArithOpDivide()
   * @generated
   */
  EReference getArithOpDivide_Rhs();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.ArithOpRemainder <em>Arith Op Remainder</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Arith Op Remainder</em>'.
   * @see org.xtext.example.mydsl.myDsl.ArithOpRemainder
   * @generated
   */
  EClass getArithOpRemainder();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.ArithOpRemainder#getLhs <em>Lhs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Lhs</em>'.
   * @see org.xtext.example.mydsl.myDsl.ArithOpRemainder#getLhs()
   * @see #getArithOpRemainder()
   * @generated
   */
  EReference getArithOpRemainder_Lhs();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.ArithOpRemainder#getRhs <em>Rhs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Rhs</em>'.
   * @see org.xtext.example.mydsl.myDsl.ArithOpRemainder#getRhs()
   * @see #getArithOpRemainder()
   * @generated
   */
  EReference getArithOpRemainder_Rhs();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.BoolOpAnd <em>Bool Op And</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Bool Op And</em>'.
   * @see org.xtext.example.mydsl.myDsl.BoolOpAnd
   * @generated
   */
  EClass getBoolOpAnd();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.BoolOpAnd#getLhs <em>Lhs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Lhs</em>'.
   * @see org.xtext.example.mydsl.myDsl.BoolOpAnd#getLhs()
   * @see #getBoolOpAnd()
   * @generated
   */
  EReference getBoolOpAnd_Lhs();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.BoolOpAnd#getRhs <em>Rhs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Rhs</em>'.
   * @see org.xtext.example.mydsl.myDsl.BoolOpAnd#getRhs()
   * @see #getBoolOpAnd()
   * @generated
   */
  EReference getBoolOpAnd_Rhs();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.BoolOpOr <em>Bool Op Or</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Bool Op Or</em>'.
   * @see org.xtext.example.mydsl.myDsl.BoolOpOr
   * @generated
   */
  EClass getBoolOpOr();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.BoolOpOr#getLhs <em>Lhs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Lhs</em>'.
   * @see org.xtext.example.mydsl.myDsl.BoolOpOr#getLhs()
   * @see #getBoolOpOr()
   * @generated
   */
  EReference getBoolOpOr_Lhs();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.BoolOpOr#getRhs <em>Rhs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Rhs</em>'.
   * @see org.xtext.example.mydsl.myDsl.BoolOpOr#getRhs()
   * @see #getBoolOpOr()
   * @generated
   */
  EReference getBoolOpOr_Rhs();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Seq <em>Seq</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Seq</em>'.
   * @see org.xtext.example.mydsl.myDsl.Seq
   * @generated
   */
  EClass getSeq();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Seq#getLhs <em>Lhs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Lhs</em>'.
   * @see org.xtext.example.mydsl.myDsl.Seq#getLhs()
   * @see #getSeq()
   * @generated
   */
  EReference getSeq_Lhs();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Seq#getRhs <em>Rhs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Rhs</em>'.
   * @see org.xtext.example.mydsl.myDsl.Seq#getRhs()
   * @see #getSeq()
   * @generated
   */
  EReference getSeq_Rhs();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.CmpOpEqual <em>Cmp Op Equal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Cmp Op Equal</em>'.
   * @see org.xtext.example.mydsl.myDsl.CmpOpEqual
   * @generated
   */
  EClass getCmpOpEqual();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.CmpOpEqual#getLhs <em>Lhs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Lhs</em>'.
   * @see org.xtext.example.mydsl.myDsl.CmpOpEqual#getLhs()
   * @see #getCmpOpEqual()
   * @generated
   */
  EReference getCmpOpEqual_Lhs();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.CmpOpEqual#getRhs <em>Rhs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Rhs</em>'.
   * @see org.xtext.example.mydsl.myDsl.CmpOpEqual#getRhs()
   * @see #getCmpOpEqual()
   * @generated
   */
  EReference getCmpOpEqual_Rhs();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.CmpOpUnequal <em>Cmp Op Unequal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Cmp Op Unequal</em>'.
   * @see org.xtext.example.mydsl.myDsl.CmpOpUnequal
   * @generated
   */
  EClass getCmpOpUnequal();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.CmpOpUnequal#getLhs <em>Lhs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Lhs</em>'.
   * @see org.xtext.example.mydsl.myDsl.CmpOpUnequal#getLhs()
   * @see #getCmpOpUnequal()
   * @generated
   */
  EReference getCmpOpUnequal_Lhs();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.CmpOpUnequal#getRhs <em>Rhs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Rhs</em>'.
   * @see org.xtext.example.mydsl.myDsl.CmpOpUnequal#getRhs()
   * @see #getCmpOpUnequal()
   * @generated
   */
  EReference getCmpOpUnequal_Rhs();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.CmpOpLess <em>Cmp Op Less</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Cmp Op Less</em>'.
   * @see org.xtext.example.mydsl.myDsl.CmpOpLess
   * @generated
   */
  EClass getCmpOpLess();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.CmpOpLess#getLhs <em>Lhs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Lhs</em>'.
   * @see org.xtext.example.mydsl.myDsl.CmpOpLess#getLhs()
   * @see #getCmpOpLess()
   * @generated
   */
  EReference getCmpOpLess_Lhs();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.CmpOpLess#getRhs <em>Rhs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Rhs</em>'.
   * @see org.xtext.example.mydsl.myDsl.CmpOpLess#getRhs()
   * @see #getCmpOpLess()
   * @generated
   */
  EReference getCmpOpLess_Rhs();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Field <em>Field</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Field</em>'.
   * @see org.xtext.example.mydsl.myDsl.Field
   * @generated
   */
  EClass getField();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Field#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Field#getName()
   * @see #getField()
   * @generated
   */
  EAttribute getField_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Field#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see org.xtext.example.mydsl.myDsl.Field#getValue()
   * @see #getField()
   * @generated
   */
  EReference getField_Value();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MyDslFactory getMyDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.FileImpl <em>File</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.FileImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getFile()
     * @generated
     */
    EClass FILE = eINSTANCE.getFile();

    /**
     * The meta object literal for the '<em><b>Commands</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FILE__COMMANDS = eINSTANCE.getFile_Commands();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.TopLevelCmdImpl <em>Top Level Cmd</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.TopLevelCmdImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getTopLevelCmd()
     * @generated
     */
    EClass TOP_LEVEL_CMD = eINSTANCE.getTopLevelCmd();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ExprImpl <em>Expr</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ExprImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getExpr()
     * @generated
     */
    EClass EXPR = eINSTANCE.getExpr();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.DefImpl <em>Def</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.DefImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getDef()
     * @generated
     */
    EClass DEF = eINSTANCE.getDef();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEF__NAME = eINSTANCE.getDef_Name();

    /**
     * The meta object literal for the '<em><b>Expr</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEF__EXPR = eINSTANCE.getDef_Expr();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.AppImpl <em>App</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.AppImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getApp()
     * @generated
     */
    EClass APP = eINSTANCE.getApp();

    /**
     * The meta object literal for the '<em><b>Lhs</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference APP__LHS = eINSTANCE.getApp_Lhs();

    /**
     * The meta object literal for the '<em><b>Rhs</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference APP__RHS = eINSTANCE.getApp_Rhs();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.VarImpl <em>Var</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.VarImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getVar()
     * @generated
     */
    EClass VAR = eINSTANCE.getVar();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VAR__NAME = eINSTANCE.getVar_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ThisImpl <em>This</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ThisImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getThis()
     * @generated
     */
    EClass THIS = eINSTANCE.getThis();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.BoolImpl <em>Bool</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.BoolImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getBool()
     * @generated
     */
    EClass BOOL = eINSTANCE.getBool();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BOOL__VALUE = eINSTANCE.getBool_Value();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.IntImpl <em>Int</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.IntImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getInt()
     * @generated
     */
    EClass INT = eINSTANCE.getInt();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INT__VALUE = eINSTANCE.getInt_Value();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.SkipImpl <em>Skip</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.SkipImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getSkip()
     * @generated
     */
    EClass SKIP = eINSTANCE.getSkip();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ProjectImpl <em>Project</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ProjectImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getProject()
     * @generated
     */
    EClass PROJECT = eINSTANCE.getProject();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROJECT__NAME = eINSTANCE.getProject_Name();

    /**
     * The meta object literal for the '<em><b>Exp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROJECT__EXP = eINSTANCE.getProject_Exp();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.BObjectImpl <em>BObject</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.BObjectImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getBObject()
     * @generated
     */
    EClass BOBJECT = eINSTANCE.getBObject();

    /**
     * The meta object literal for the '<em><b>Fields</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BOBJECT__FIELDS = eINSTANCE.getBObject_Fields();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.CopyImpl <em>Copy</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.CopyImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getCopy()
     * @generated
     */
    EClass COPY = eINSTANCE.getCopy();

    /**
     * The meta object literal for the '<em><b>Copy</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COPY__COPY = eINSTANCE.getCopy_Copy();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.WithImpl <em>With</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.WithImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getWith()
     * @generated
     */
    EClass WITH = eINSTANCE.getWith();

    /**
     * The meta object literal for the '<em><b>Lhs</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WITH__LHS = eINSTANCE.getWith_Lhs();

    /**
     * The meta object literal for the '<em><b>Rhs</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WITH__RHS = eINSTANCE.getWith_Rhs();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.NotImpl <em>Not</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.NotImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getNot()
     * @generated
     */
    EClass NOT = eINSTANCE.getNot();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NOT__VALUE = eINSTANCE.getNot_Value();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.IfImpl <em>If</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.IfImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getIf()
     * @generated
     */
    EClass IF = eINSTANCE.getIf();

    /**
     * The meta object literal for the '<em><b>Cond</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IF__COND = eINSTANCE.getIf_Cond();

    /**
     * The meta object literal for the '<em><b>Thn</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IF__THN = eINSTANCE.getIf_Thn();

    /**
     * The meta object literal for the '<em><b>Els</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IF__ELS = eINSTANCE.getIf_Els();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.LetImpl <em>Let</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.LetImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getLet()
     * @generated
     */
    EClass LET = eINSTANCE.getLet();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LET__NAME = eINSTANCE.getLet_Name();

    /**
     * The meta object literal for the '<em><b>Lhs</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LET__LHS = eINSTANCE.getLet_Lhs();

    /**
     * The meta object literal for the '<em><b>Rhs</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LET__RHS = eINSTANCE.getLet_Rhs();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.FunImpl <em>Fun</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.FunImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getFun()
     * @generated
     */
    EClass FUN = eINSTANCE.getFun();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FUN__NAME = eINSTANCE.getFun_Name();

    /**
     * The meta object literal for the '<em><b>Body</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUN__BODY = eINSTANCE.getFun_Body();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.AssignImpl <em>Assign</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.AssignImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getAssign()
     * @generated
     */
    EClass ASSIGN = eINSTANCE.getAssign();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ASSIGN__NAME = eINSTANCE.getAssign_Name();

    /**
     * The meta object literal for the '<em><b>Lhs</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ASSIGN__LHS = eINSTANCE.getAssign_Lhs();

    /**
     * The meta object literal for the '<em><b>Rhs</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ASSIGN__RHS = eINSTANCE.getAssign_Rhs();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ArithOpPlusImpl <em>Arith Op Plus</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ArithOpPlusImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getArithOpPlus()
     * @generated
     */
    EClass ARITH_OP_PLUS = eINSTANCE.getArithOpPlus();

    /**
     * The meta object literal for the '<em><b>Lhs</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ARITH_OP_PLUS__LHS = eINSTANCE.getArithOpPlus_Lhs();

    /**
     * The meta object literal for the '<em><b>Rhs</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ARITH_OP_PLUS__RHS = eINSTANCE.getArithOpPlus_Rhs();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ArithOpMinusImpl <em>Arith Op Minus</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ArithOpMinusImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getArithOpMinus()
     * @generated
     */
    EClass ARITH_OP_MINUS = eINSTANCE.getArithOpMinus();

    /**
     * The meta object literal for the '<em><b>Lhs</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ARITH_OP_MINUS__LHS = eINSTANCE.getArithOpMinus_Lhs();

    /**
     * The meta object literal for the '<em><b>Rhs</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ARITH_OP_MINUS__RHS = eINSTANCE.getArithOpMinus_Rhs();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ArithOpTimesImpl <em>Arith Op Times</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ArithOpTimesImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getArithOpTimes()
     * @generated
     */
    EClass ARITH_OP_TIMES = eINSTANCE.getArithOpTimes();

    /**
     * The meta object literal for the '<em><b>Lhs</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ARITH_OP_TIMES__LHS = eINSTANCE.getArithOpTimes_Lhs();

    /**
     * The meta object literal for the '<em><b>Rhs</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ARITH_OP_TIMES__RHS = eINSTANCE.getArithOpTimes_Rhs();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ArithOpDivideImpl <em>Arith Op Divide</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ArithOpDivideImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getArithOpDivide()
     * @generated
     */
    EClass ARITH_OP_DIVIDE = eINSTANCE.getArithOpDivide();

    /**
     * The meta object literal for the '<em><b>Lhs</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ARITH_OP_DIVIDE__LHS = eINSTANCE.getArithOpDivide_Lhs();

    /**
     * The meta object literal for the '<em><b>Rhs</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ARITH_OP_DIVIDE__RHS = eINSTANCE.getArithOpDivide_Rhs();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ArithOpRemainderImpl <em>Arith Op Remainder</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ArithOpRemainderImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getArithOpRemainder()
     * @generated
     */
    EClass ARITH_OP_REMAINDER = eINSTANCE.getArithOpRemainder();

    /**
     * The meta object literal for the '<em><b>Lhs</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ARITH_OP_REMAINDER__LHS = eINSTANCE.getArithOpRemainder_Lhs();

    /**
     * The meta object literal for the '<em><b>Rhs</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ARITH_OP_REMAINDER__RHS = eINSTANCE.getArithOpRemainder_Rhs();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.BoolOpAndImpl <em>Bool Op And</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.BoolOpAndImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getBoolOpAnd()
     * @generated
     */
    EClass BOOL_OP_AND = eINSTANCE.getBoolOpAnd();

    /**
     * The meta object literal for the '<em><b>Lhs</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BOOL_OP_AND__LHS = eINSTANCE.getBoolOpAnd_Lhs();

    /**
     * The meta object literal for the '<em><b>Rhs</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BOOL_OP_AND__RHS = eINSTANCE.getBoolOpAnd_Rhs();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.BoolOpOrImpl <em>Bool Op Or</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.BoolOpOrImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getBoolOpOr()
     * @generated
     */
    EClass BOOL_OP_OR = eINSTANCE.getBoolOpOr();

    /**
     * The meta object literal for the '<em><b>Lhs</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BOOL_OP_OR__LHS = eINSTANCE.getBoolOpOr_Lhs();

    /**
     * The meta object literal for the '<em><b>Rhs</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BOOL_OP_OR__RHS = eINSTANCE.getBoolOpOr_Rhs();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.SeqImpl <em>Seq</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.SeqImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getSeq()
     * @generated
     */
    EClass SEQ = eINSTANCE.getSeq();

    /**
     * The meta object literal for the '<em><b>Lhs</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SEQ__LHS = eINSTANCE.getSeq_Lhs();

    /**
     * The meta object literal for the '<em><b>Rhs</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SEQ__RHS = eINSTANCE.getSeq_Rhs();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.CmpOpEqualImpl <em>Cmp Op Equal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.CmpOpEqualImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getCmpOpEqual()
     * @generated
     */
    EClass CMP_OP_EQUAL = eINSTANCE.getCmpOpEqual();

    /**
     * The meta object literal for the '<em><b>Lhs</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CMP_OP_EQUAL__LHS = eINSTANCE.getCmpOpEqual_Lhs();

    /**
     * The meta object literal for the '<em><b>Rhs</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CMP_OP_EQUAL__RHS = eINSTANCE.getCmpOpEqual_Rhs();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.CmpOpUnequalImpl <em>Cmp Op Unequal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.CmpOpUnequalImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getCmpOpUnequal()
     * @generated
     */
    EClass CMP_OP_UNEQUAL = eINSTANCE.getCmpOpUnequal();

    /**
     * The meta object literal for the '<em><b>Lhs</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CMP_OP_UNEQUAL__LHS = eINSTANCE.getCmpOpUnequal_Lhs();

    /**
     * The meta object literal for the '<em><b>Rhs</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CMP_OP_UNEQUAL__RHS = eINSTANCE.getCmpOpUnequal_Rhs();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.CmpOpLessImpl <em>Cmp Op Less</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.CmpOpLessImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getCmpOpLess()
     * @generated
     */
    EClass CMP_OP_LESS = eINSTANCE.getCmpOpLess();

    /**
     * The meta object literal for the '<em><b>Lhs</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CMP_OP_LESS__LHS = eINSTANCE.getCmpOpLess_Lhs();

    /**
     * The meta object literal for the '<em><b>Rhs</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CMP_OP_LESS__RHS = eINSTANCE.getCmpOpLess_Rhs();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.FieldImpl <em>Field</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.FieldImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getField()
     * @generated
     */
    EClass FIELD = eINSTANCE.getField();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FIELD__NAME = eINSTANCE.getField_Name();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FIELD__VALUE = eINSTANCE.getField_Value();

  }

} //MyDslPackage
