/*
 * generated by Xtext 2.14.0
 */
package org.tetrabox.minijava.xtext.fortest.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MiniJavaAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/tetrabox/minijava/xtext/fortest/parser/antlr/internal/InternalMiniJava.tokens");
	}
}
