/*
 * generated by Xtext 2.14.0
 */
package imp.lang.xtext


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class ImpRuntimeModule extends AbstractImpRuntimeModule {
}
