/*
 * generated by Xtext 2.14.0
 */
package boa.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractBoaScopeProvider extends DelegatingScopeProvider {
}
