<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="test1" nsURI="http://test1" nsPrefix="test1">
  <eClassifiers xsi:type="ecore:EClass" name="ConceptA">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cs" upperBound="-1" eType="#//ConceptC"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConceptB" eSuperTypes="#//ConceptA"/>
  <eClassifiers xsi:type="ecore:EClass" name="ConceptC">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nbr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
</ecore:EPackage>
