/*
 * generated by Xtext 2.14.0
 */
package boa.xtext


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class BoaRuntimeModule extends AbstractBoaRuntimeModule {
}
