/*
 * generated by Xtext 2.14.0
 */
package boa.xtext


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class BoaStandaloneSetup extends BoaStandaloneSetupGenerated {

	def static void doSetup() {
		new BoaStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
