/*
 * generated by Xtext 2.14.0
 */
package org.tetrabox.minijava.xtext.fortest.tests

import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(MiniJavaInjectorProvider)
class MiniJavaParsingTest {

	@Test
	def void loadModel() {
	}
}
