/*
 * generated by Xtext 2.14.0
 */
package boa.xtext.parser.antlr;

import boa.xtext.parser.antlr.internal.InternalBoaParser;
import boa.xtext.services.BoaGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class BoaParser extends AbstractAntlrParser {

	@Inject
	private BoaGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalBoaParser createParser(XtextTokenStream stream) {
		return new InternalBoaParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "File";
	}

	public BoaGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(BoaGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
