/*
 * generated by Xtext 2.14.0
 */
package org.tetrabox.minijava.xtext.fortest


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MiniJavaStandaloneSetup extends MiniJavaStandaloneSetupGenerated {

	def static void doSetup() {
		new MiniJavaStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
