/*
 * generated by Xtext 2.14.0
 */
package org.tetrabox.minijava.xtext.fortest


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class MiniJavaRuntimeModule extends AbstractMiniJavaRuntimeModule {
}
