/*
 * generated by Xtext 2.14.0
 */
package boa.xtext.ide

import boa.xtext.BoaRuntimeModule
import boa.xtext.BoaStandaloneSetup
import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class BoaIdeSetup extends BoaStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new BoaRuntimeModule, new BoaIdeModule))
	}
	
}
