/*
 * generated by Xtext 2.14.0
 */
package org.tetrabox.minijava.xtext.fortest.ide


/**
 * Use this class to register ide components.
 */
class MiniJavaIdeModule extends AbstractMiniJavaIdeModule {
}
