/*
 * generated by Xtext 2.14.0
 */
package imp.lang.xtext.ide

import com.google.inject.Guice
import imp.lang.xtext.ImpRuntimeModule
import imp.lang.xtext.ImpStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class ImpIdeSetup extends ImpStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new ImpRuntimeModule, new ImpIdeModule))
	}
	
}
